[package]
name = "qopy"
version = "0.1.0"
description = "Qopy"
authors = ["pandadev"]
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "2.0.0-beta.18", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.23", features = ["unstable", "tray-icon", "image-png"] }
tauri-plugin-sql = {version = "2.0.0-beta.8", features = ["sqlite"] }
tauri-plugin-clipboard-manager = "2.1.0-beta.5"
tauri-plugin-global-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-autostart = "2.0.0-beta.8"
tauri-plugin-os = "2.0.0-beta.7"
sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "sqlite"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
rdev = "0.5.3"
rand = "0.8"
base64 = "0.22.1"
arboard = "3.4.0"
image = "0.25.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
url = "2.5.2"
log = "0.4"
simplelog = "0.12.2"
regex = "1"