[package]
name = "qopy"
version = "0.1.1"
description = "Qopy"
authors = ["pandadev"]
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.0", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.0", features = ["tray-icon", "image-png"] }
tauri-plugin-sql = {version = "2.0.0-rc.0", features = ["sqlite"] }
tauri-plugin-clipboard-manager = "2.0.0-rc.0"
tauri-plugin-autostart = "2.0.0-rc.0"
tauri-plugin-os = "2.0.0-rc.0"
tauri-plugin-updater = "2.0.0-rc.0"
tauri-plugin-dialog = "2.0.0-rc.0"
tauri-plugin-prevent-default = "0.3.0"
sqlx = { version = "0.8.0", features = ["runtime-tokio-native-tls", "sqlite"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
rdev = "0.5.3"
rand = "0.8"
base64 = "0.22.1"
arboard = "3.4.0"
image = "0.25.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
url = "2.5.2"
regex = "1"
sha2 = "0.10.6"
lazy_static = "1.4.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
